package com.github.onran0.passer.cli.commands;

import com.github.onran0.passer.cli.commands.core.PasswordBasedCommand;
import com.github.onran0.passer.core.PasserCore;
import com.github.onran0.passer.core.PasswordInfo;
import com.github.onran0.passer.core.PasswordType;
import com.github.onran0.passer.security.RuntimeSecurity;
import joptsimple.OptionParser;
import joptsimple.OptionSet;
import joptsimple.util.EnumConverter;

public class AddCommand extends PasswordBasedCommand {

    @Override
    protected void initializeParser(OptionParser parser) {
        parser.accepts("c", "Caption of password")
                .withRequiredArg()
                .ofType(String.class)
                .required();

        parser.accepts("l", "Login of password")
                .withRequiredArg()
                .ofType(String.class);

        parser.accepts("s", "Service of password")
                .withRequiredArg()
                .ofType(String.class);

        parser.accepts("g", "Specify that the password should be generated automatically");

        parser.accepts("t", "Type of password")
                .withRequiredArg()
                .withValuesConvertedBy(new EnumConverter<>(PasswordType.class) {
                    @Override
                    public PasswordType convert(String value) {
                        return PasswordType.fromName(value);
                    }
                });
    }

    @Override
    public void execute(OptionSet options) {
        super.execute(options);

        if(checkNotOpen())
            return;

        String caption = (String) options.valueOf("c");
        PasswordType type = (PasswordType) options.valueOf("t");

        if(type == null)
            type = PasswordType.TEXT;

        byte[] password = null;

        if(!options.has("g")) {
            char[] passwordInput = requestPassword(type == PasswordType.BINARY);

            password = extractBytesFromInputPassword(passwordInput, new int[] { type.getID() });

            RuntimeSecurity.clear(passwordInput);

            if(password == null) {
                invalidUsage("incorrect command usage");
                return;
            }
        }

        boolean isAutogeneratedPassword = password == null;

        if(password == null)
            password = generatePassword(new int[] { type.getID() });

        long creationTime = System.currentTimeMillis();

        this.passes.getPasses().add(new PasswordInfo(
                caption.toCharArray(),
                PasserCore.MISSING_PROPERTY_DEFAULT.clone(),
                PasserCore.MISSING_PROPERTY_DEFAULT.clone(),
                new boolean[] { isAutogeneratedPassword },
                new int[] { type.ordinal() },
                password,
                new long[] { creationTime },
                new long[] { creationTime }
        ));

        getOut().printf("new password with caption \"%s\" successfully added and its id is \"%d\"\n", caption, this.passes.getPasses().size() - 1);

        fileSaved = false;
    }
}