/*
 *     Passer - is a minimalist CLI password manager focused on security, transparency, and full control over your data
 *     Copyright (C) 2026  Onran
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.github.onran0.passer.core;

import com.github.onran0.passer.security.*;

public class PasswordInfo {

    private SecuredCharArray caption;
    private SecuredCharArray service;
    private SecuredCharArray login;
    private SecuredBool autogeneratedPassword;
    private SecuredByteArray password;
    private final SecuredInt passwordType;
    private final SecuredLong creationTime;
    private SecuredLong modificationTime;

    public PasswordInfo(
            char[] caption,
            char[] service,
            char[] login,
            boolean[] autogeneratedPassword,
            int[] passwordType,
            byte[] password,
            long[] creationTime,
            long[] modificationTime
    ) {
        this.caption = new SecuredCharArray(caption);
        this.service = new SecuredCharArray(service);
        this.login = new SecuredCharArray(login);
        this.autogeneratedPassword = new SecuredBool(autogeneratedPassword);
        this.passwordType = new SecuredInt(passwordType);
        this.password = new SecuredByteArray(password);
        this.creationTime = new SecuredLong(creationTime);
        this.modificationTime = new SecuredLong(modificationTime);
    }

    public char[] getCaption() {
        return caption.getDecryptedData();
    }

    public char[] getService() {
        return service.getDecryptedData();
    }

    public char[] getLogin() {
        return login.getDecryptedData();
    }

    public void setCaption(char[] caption) {
        this.caption = new SecuredCharArray(caption);
    }

    public void setService(char[] service) {
        this.service = new SecuredCharArray(service);
    }

    public void setLogin(char[] login) {
        this.login = new SecuredCharArray(login);
    }

    public boolean[] isAutogeneratedPassword() {
        return autogeneratedPassword.getDecryptedData();
    }

    public void setAutogeneratedPassword(boolean[] autogeneratedPassword) {
        this.autogeneratedPassword = new SecuredBool(autogeneratedPassword);
    }

    public int[] getPasswordType() {
        return passwordType.getDecryptedData();
    }

    public byte[] getPassword() {
        return password.getDecryptedData();
    }

    public void setPassword(byte[] password) {
        this.password = new SecuredByteArray(password);
    }

    public long[] getCreationTime() {
        return creationTime.getDecryptedData();
    }

    public long[] getModificationTime() {
        return modificationTime.getDecryptedData();
    }

    public void setModificationTime(long[] modificationTime) {
        this.modificationTime = new SecuredLong(modificationTime);
    }
}